//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Xomega Data Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using AdventureWorks.Services;
using Microsoft.Extensions.DependencyInjection;
using System;
using Xomega.Framework;
using Xomega.Framework.Properties;
using Xomega.Framework.Services;

namespace AdventureWorks.Client.Objects
{
    public partial class AuthenticationObject : DataObject
    {
        #region Constants

        public const string Email = "Email";
        public const string Password = "Password";

        #endregion

        #region Properties

        public TextProperty EmailProperty { get; private set; }
        public TextProperty PasswordProperty { get; private set; }

        #endregion

        #region Construction

        public AuthenticationObject()
        {
        }

        public AuthenticationObject(IServiceProvider serviceProvider) : base(serviceProvider)
        {
        }

        protected override void Initialize()
        {
            EmailProperty = new TextProperty(this, Email);
            EmailProperty.Required = true;
            EmailProperty.Size = 50;
            PasswordProperty = new TextProperty(this, Password);
            PasswordProperty.Required = true;
        }

        #endregion

        #region CRUD Operations

        protected override ErrorList DoSave(object options)
        {
            var output = Person_Authenticate(options);
            return output.Messages;
        }

        #endregion

        #region Service Operations

        protected virtual Output Person_Authenticate(object options)
        {
            Credentials _credentials = ToDataContract<Credentials>(options);
            using (var s = ServiceProvider.CreateScope())
            {
                var output = s.ServiceProvider.GetService<IPersonService>().Authenticate(_credentials);

                return output;
            }
        }

        #endregion
    }
}