//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "SPA Views" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

require.config({
    paths: {
        'LoginView': 'Views/Person/LoginViewCustomized',
        'CustomerListView': 'Views/Sales/CustomerListView',
        'SalesOrderView': 'Views/Sales/SalesOrderViewCustomized',
        'SalesOrderListView': 'Views/Sales/SalesOrderListViewCustomized',
        'SalesOrderDetailView': 'Views/Sales/SalesOrderDetailView',
    }
});