//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "TS Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

import * as $ from 'jquery';
import { AuthManager } from 'xomega';

export class IProductService {

    public static getReadListAsyncRequest(): JQueryAjaxSettings {
        let req: JQueryAjaxSettings = AuthManager.Current.createAjaxRequest();
        req.type = 'GET';
        req.url += `product`;
        return req;
    }
}

export class Product_ReadListOutput {
    public ProductId: any = null;
    public Name: any = null;
    public IsActive: any = null;
    public ProductSubcategoryId: any = null;
    public ProductModelId: any = null;
    public ListPrice: any = null;
}