//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "TS Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

import * as $ from 'jquery';
import { AuthManager } from 'xomega';

export class IProductSubcategoryService {

    public static getReadListAsyncRequest(): JQueryAjaxSettings {
        let req: JQueryAjaxSettings = AuthManager.Current.createAjaxRequest();
        req.type = 'GET';
        req.url += `product-subcategory`;
        return req;
    }
}

export class ProductSubcategory_ReadListOutput {
    public ProductSubcategoryId: any = null;
    public ProductCategoryId: any = null;
    public Name: any = null;
}