//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    public partial class EmployeeTemporal
    {
        public EmployeeTemporal()
        {
        }

        #region Properties

        public int BusinessEntityId  { get; set; }

        public string NationalIdNumber  { get; set; }

        public string LoginId  { get; set; }

        public short? OrganizationLevel  { get; set; }

        public string JobTitle  { get; set; }

        public DateTime BirthDate  { get; set; }

        public string MaritalStatus  { get; set; }

        public string Gender  { get; set; }

        public DateTime HireDate  { get; set; }

        public short VacationHours  { get; set; }

        public short SickLeaveHours  { get; set; }

        public DateTime ValidFrom  { get; set; }

        public DateTime ValidTo  { get; set; }

        #endregion
    }
}