//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "TS Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

import * as $ from 'jquery';
import { AuthManager } from 'xomega';

export class ICustomerService {

    public static getReadListAsyncRequest(_criteria: Customer_ReadListInput_Criteria): JQueryAjaxSettings {
        let req: JQueryAjaxSettings = AuthManager.Current.createAjaxRequest();
        req.type = 'GET';
        req.url += `customer?${ $.param(_criteria, true) }`;
        return req;
    }
}

export class Customer_ReadListInput_Criteria {
    public TerritoryId: any = null;
    public PersonNameOperator: any = null;
    public PersonName: any = null;
    public StoreNameOperator: any = null;
    public StoreName: any = null;
    public AccountNumberOperator: any = null;
    public AccountNumber: any = null;
}

export class Customer_ReadListOutput {
    public CustomerId: any = null;
    public StoreId: any = null;
    public StoreName: any = null;
    public PersonId: any = null;
    public PersonName: any = null;
    public AccountNumber: any = null;
    public TerritoryId: any = null;
}