//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "TS Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

import * as $ from 'jquery';
import { AuthManager } from 'xomega';

export class IPersonCreditCardService {

    public static getReadListAsyncRequest(_businessEntityId: any): JQueryAjaxSettings {
        let req: JQueryAjaxSettings = AuthManager.Current.createAjaxRequest();
        req.type = 'GET';
        req.url += `person/${ _businessEntityId }/credit-card`;
        return req;
    }
}

export class PersonCreditCard_ReadListOutput {
    public CreditCardId: any = null;
    public CreditCardName: any = null;
    public PersonName: any = null;
    public CardType: any = null;
    public CardNumber: any = null;
    public ExpMonth: any = null;
    public ExpYear: any = null;
}