//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "WPF Views" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using AdventureWorks.Client.ViewModels;
using System.Windows;
using System.Windows.Controls;
using Xomega.Framework.Views;

namespace AdventureWorks.Client.Wpf
{
    public partial class CustomerListView
    {
        protected CustomerListViewModel VM => Model as CustomerListViewModel;

        public CustomerListView()
        {
            InitializeComponent();
            IsAsync = true;
        }

        protected override TextBlock TitleControl => viewTitle;
        protected override Button CloseButton => btnClose;
        protected override IErrorPresenter ErrorsPanel => pnlErrors;
        protected override Button SearchButton => btnSearch;
        protected override Button SelectButton => btnSelect;

        protected override ItemsControl ResultsGrid => gridResults;
        protected override Button ResetButton => btnReset;
        protected override IAppliedCriteriaPanel AppliedCriteriaPanel => pnlAppliedCriteria;
        protected override ICollapsiblePanel CriteriaExpander => new ExpanderCollapsiblePanel(pnlCriteria);
        protected override FrameworkElement CriteriaPanel => pnlCriteria;
        protected override ContentControl ChildPanel => pnlDetails;
    }
}