//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "WPF Views" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System.Windows.Controls;
using Xomega.Framework.Views;

namespace AdventureWorks.Client.Wpf
{
    public partial class SalesOrderDetailView
    {
        public SalesOrderDetailView()
        {
            InitializeComponent();
        }

        protected override Button CloseButton { get { return btnClose; } }
        protected override IErrorPresenter ErrorsPanel { get { return pnlErrors; } }
        protected override Button DeleteButton { get { return btnDelete; } }
        protected override Button SaveButton { get { return btnSave; } }
    }
}