//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "TS Enumeration Constants" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

// Generated constants for all enumerations as classes with the enumeration name 
// stored in a special field EnumName and other items declared as static fields.
// Additional attributes are declared inside "nested" classes Attributes.

export class BusinessEntityAddress {
    public static EnumName: string = "business entity address";

}
export module BusinessEntityAddress {
    export class Attributes
    {
        public static AddressLine1: string = "address line 1";
        public static AddressLine2: string = "address line 2";
        public static City: string = "city";
        public static State: string = "state";
        public static PostalCode: string = "postal code";
        public static Country: string = "country";
    }
}

export class Operators {
    public static EnumName: string = "operators";

    public static IsNull: string = "NL";
    public static IsNotNull: string = "NNL";
    public static IsEqualTo: string = "EQ";
    public static IsNotEqualTo: string = "NEQ";
    public static IsOneOf: string = "In";
    public static IsNoneOf: string = "NIn";
    public static IsLessThan: string = "LT";
    public static IsLessThanOrEqualTo: string = "LE";
    public static IsGreaterThan: string = "GT";
    public static IsGreaterThanOrEqualTo: string = "GE";
    public static Today: string = "[bod,eod)";
    public static ThisWeek: string = "[bow,eow)";
    public static ThisMonth: string = "[boM,eoM)";
    public static ThisYear: string = "[boy,eoy)";
    public static Last30Days: string = "[bod-30d,ct]";
    public static IsEarlierThan: string = "Earlier";
    public static IsLaterThan: string = "Later";
    public static Contains: string = "CN";
    public static DoesNotContain: string = "NCN";
    public static StartsWith: string = "SW";
    public static DoesNotStartWith: string = "NSW";
    public static IsBetween: string = "BW";
    public static IsNotBetween: string = "NBW";
}
export module Operators {
    export class Attributes
    {
        public static SortOrder: string = "sort order";
        public static AddlProps: string = "addl props";
        public static Multival: string = "multival";
        public static Type: string = "type";
        public static ExcludeType: string = "exclude type";
        public static NullCheck: string = "null check";
    }
}

export class PersonCreditCard {
    public static EnumName: string = "person credit card";

}
export module PersonCreditCard {
    export class Attributes
    {
        public static PersonName: string = "person name";
        public static CardType: string = "card type";
        public static CardNumber: string = "card number";
        public static ExpMonth: string = "exp month";
        public static ExpYear: string = "exp year";
    }
}

export class PersonType {
    public static EnumName: string = "person type";

    public static StoreContact: string = "SC";
    public static IndividualCustomer: string = "IN";
    public static SalesPerson: string = "SP";
    public static Employee: string = "EM";
    public static VendorContact: string = "VC";
    public static GeneralContact: string = "GC";
}
export class Product {
    public static EnumName: string = "product";

}
export module Product {
    export class Attributes
    {
        public static ProductSubcategoryId: string = "product subcategory id";
        public static ProductModelId: string = "product model id";
    }
}

export class SalesOrderStatus {
    public static EnumName: string = "sales order status";

    public static InProcess: string = "1";
    public static Approved: string = "2";
    public static Backordered: string = "3";
    public static Rejected: string = "4";
    public static Shipped: string = "5";
    public static Cancelled: string = "6";
}
export class SalesPerson {
    public static EnumName: string = "sales person";

}
export module SalesPerson {
    export class Attributes
    {
        public static TerritoryId: string = "territory id";
    }
}

export class SalesReason {
    public static EnumName: string = "sales reason";

}
export class SalesTerritory {
    public static EnumName: string = "sales territory";

}
export module SalesTerritory {
    export class Attributes
    {
        public static CountryRegionCode: string = "country region code";
        public static Group: string = "group";
    }
}

export class SalesTerritoryGroup {
    public static EnumName: string = "sales territory group";

    public static NorthAmerica: string = "North America";
    public static Europe: string = "Europe";
    public static Pacific: string = "Pacific";
}
export class ShipMethod {
    public static EnumName: string = "ship method";

}
export class SpecialOffer {
    public static EnumName: string = "special offer";

}
export module SpecialOffer {
    export class Attributes
    {
        public static Category: string = "category";
    }
}

export class Yesno {
    public static EnumName: string = "yesno";

    public static Yes: string = "true";
    public static No: string = "false";
}