//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Web API Controllers" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using Xomega.Framework;
using Xomega.Framework.Services;

namespace AdventureWorks.Services.Rest
{
    ///<summary>
    /// Current customer information. Also see the Person and Store tables.
    ///</summary>
    public partial class CustomerController : ControllerBase
    {
        private ErrorList currentErrors;
        private ErrorParser errorsParser;
        private ICustomerService svc;

        public CustomerController(ErrorList errorList, ErrorParser errorParser, ICustomerService service)
        {
            currentErrors = errorList;
            errorsParser = errorParser;
            svc = service;
        }

        ///<summary>
        /// Reads a list of Customer objects based on the specified criteria.
        ///</summary>
        [Route("customer")]
        [HttpGet]
        public ActionResult ReadList([FromQuery] Customer_ReadListInput_Criteria _criteria)
        {
            ActionResult response = null;
            try
            {
                if (ModelState.IsValid)
                {
                    Output<ICollection<Customer_ReadListOutput>> output = svc.ReadList(_criteria);
                    response = StatusCode((int)output.HttpStatus, output);
                    return response;
                }
                else
                {
                    ModelValidation.AddModelErrors(currentErrors, ModelState);
                }
            }
            catch (Exception ex)
            {
                currentErrors.MergeWith(errorsParser.FromException(ex));
            }
            response = StatusCode((int)currentErrors.HttpStatus, new Output(currentErrors));
            return response;
        }
    }
}