//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "XomegaJS Data Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

import { DataObject, EnumIntProperty } from 'xomega';

export class SalesOrderSalesObject extends DataObject {

    // Properties
    public SalesPersonId: EnumIntProperty;
    public SalesReason: EnumIntProperty;
    public TerritoryId: EnumIntProperty;

    // Construction and initialization
    init() {
        this.SalesPersonId = new EnumIntProperty();
        this.SalesPersonId.EnumType = "sales person";
        this.SalesReason = new EnumIntProperty();
        this.SalesReason.IsMultiValued = true;
        this.SalesReason.EnumType = "sales reason";
        this.TerritoryId = new EnumIntProperty();
        this.TerritoryId.EnumType = "sales territory";
    }
}
