//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "XomegaJS Data Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

import { CriteriaObject, TextProperty, OperatorProperty, DateProperty, EnumIntProperty, MoneyProperty } from 'xomega';

export class SalesOrderCriteria extends CriteriaObject {

    // Properties
    public CustomerName: TextProperty;
    public CustomerNameOperator: OperatorProperty;
    public CustomerStore: TextProperty;
    public CustomerStoreOperator: OperatorProperty;
    public DueDate: DateProperty;
    public DueDate2: DateProperty;
    public DueDateOperator: OperatorProperty;
    public OrderDate: DateProperty;
    public OrderDate2: DateProperty;
    public OrderDateOperator: OperatorProperty;
    public SalesOrderNumber: TextProperty;
    public SalesOrderNumberOperator: OperatorProperty;
    public SalesPersonId: EnumIntProperty;
    public SalesPersonIdOperator: OperatorProperty;
    public Status: EnumIntProperty;
    public StatusOperator: OperatorProperty;
    public TerritoryId: EnumIntProperty;
    public TerritoryIdOperator: OperatorProperty;
    public TotalDue: MoneyProperty;
    public TotalDue2: MoneyProperty;
    public TotalDueOperator: OperatorProperty;

    // Construction and initialization
    init() {
        this.CustomerName = new TextProperty();
        this.CustomerNameOperator = new OperatorProperty();
        this.CustomerNameOperator.Size = 25;
        this.CustomerNameOperator.EnumType = "operators";
        this.CustomerNameOperator.HasNullCheck = true;
        this.CustomerStore = new TextProperty();
        this.CustomerStoreOperator = new OperatorProperty();
        this.CustomerStoreOperator.Size = 25;
        this.CustomerStoreOperator.EnumType = "operators";
        this.CustomerStoreOperator.HasNullCheck = true;
        this.DueDate = new DateProperty();
        this.DueDate2 = new DateProperty();
        this.DueDateOperator = new OperatorProperty();
        this.DueDateOperator.Size = 25;
        this.DueDateOperator.EnumType = "operators";
        this.OrderDate = new DateProperty();
        this.OrderDate2 = new DateProperty();
        this.OrderDateOperator = new OperatorProperty();
        this.OrderDateOperator.Size = 25;
        this.OrderDateOperator.EnumType = "operators";
        this.SalesOrderNumber = new TextProperty();
        this.SalesOrderNumber.Size = 25;
        this.SalesOrderNumberOperator = new OperatorProperty();
        this.SalesOrderNumberOperator.Size = 25;
        this.SalesOrderNumberOperator.EnumType = "operators";
        this.SalesPersonId = new EnumIntProperty();
        this.SalesPersonId.IsMultiValued = true;
        this.SalesPersonId.EnumType = "sales person";
        this.SalesPersonIdOperator = new OperatorProperty();
        this.SalesPersonIdOperator.Size = 25;
        this.SalesPersonIdOperator.EnumType = "operators";
        this.SalesPersonIdOperator.HasNullCheck = true;
        this.Status = new EnumIntProperty();
        this.Status.IsMultiValued = true;
        this.Status.EnumType = "sales order status";
        this.StatusOperator = new OperatorProperty();
        this.StatusOperator.Size = 25;
        this.StatusOperator.EnumType = "operators";
        this.TerritoryId = new EnumIntProperty();
        this.TerritoryId.EnumType = "sales territory";
        this.TerritoryIdOperator = new OperatorProperty();
        this.TerritoryIdOperator.Size = 25;
        this.TerritoryIdOperator.EnumType = "operators";
        this.TerritoryIdOperator.HasNullCheck = true;
        this.TotalDue = new MoneyProperty();
        this.TotalDue2 = new MoneyProperty();
        this.TotalDueOperator = new OperatorProperty();
        this.TotalDueOperator.Size = 25;
        this.TotalDueOperator.EnumType = "operators";
    }
}
