//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "TS Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

import * as $ from 'jquery';
import { AuthManager } from 'xomega';

export class IBusinessEntityAddressService {

    public static getReadListAsyncRequest(_businessEntityId: any): JQueryAjaxSettings {
        let req: JQueryAjaxSettings = AuthManager.Current.createAjaxRequest();
        req.type = 'GET';
        req.url += `business entity/${ _businessEntityId }/address`;
        return req;
    }
}

export class BusinessEntityAddress_ReadListOutput {
    public AddressId: any = null;
    public AddressType: any = null;
    public AddressLine1: any = null;
    public AddressLine2: any = null;
    public City: any = null;
    public State: any = null;
    public PostalCode: any = null;
    public Country: any = null;
}