//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Web API Controllers" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xomega.Framework;
using Xomega.Framework.Services;

namespace AdventureWorks.Services.Rest
{
    ///<summary>
    /// Cross-reference table mapping customers, vendors, and employees to their addresses.
    ///</summary>
    public partial class BusinessEntityAddressController : BaseController
    {
        private readonly IBusinessEntityAddressService svc;

        public BusinessEntityAddressController(ErrorList errorList, ErrorParser errorParser, IBusinessEntityAddressService service)
            : base(errorList, errorParser)
        {
            svc = service;
        }

        ///<summary>
        /// Reads a list of Business Entity Address objects based on the specified criteria.
        ///</summary>
        [Route("business-entity/{_businessEntityId}/address")]
        [HttpGet]
        public async Task<ActionResult> ReadListAsync([FromRoute] int _businessEntityId)
        {
            ActionResult response;
            try
            {
                if (ModelState.IsValid)
                {
                    Output<ICollection<BusinessEntityAddress_ReadListOutput>> output = await svc.ReadListAsync(_businessEntityId);
                    response = StatusCode((int)output.HttpStatus, output);
                    return response;
                }
                else
                {
                    currentErrors.AddModelErrors(ModelState);
                }
            }
            catch (Exception ex)
            {
                currentErrors.MergeWith(errorsParser.FromException(ex));
            }
            response = StatusCode((int)currentErrors.HttpStatus, new Output(currentErrors));
            return response;
        }
    }
}