//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Web API Controllers" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using Xomega.Framework;
using Xomega.Framework.Services;

namespace AdventureWorks.Services.Rest
{
    ///<summary>
    /// Cross-reference table mapping customers, vendors, and employees to their addresses.
    ///</summary>
    public partial class BusinessEntityAddressController : ControllerBase
    {
        private ErrorList currentErrors;
        private ErrorParser errorsParser;
        private IBusinessEntityAddressService svc;

        public BusinessEntityAddressController(ErrorList errorList, ErrorParser errorParser, IBusinessEntityAddressService service)
        {
            currentErrors = errorList;
            errorsParser = errorParser;
            svc = service;
        }

        [Route("business entity/{_businessEntityId}/address")]
        [HttpGet]
        public ActionResult ReadList([FromRoute] int _businessEntityId)
        {
            ActionResult response = null;
            try
            {
                if (ModelState.IsValid)
                {
                    Output<ICollection<BusinessEntityAddress_ReadListOutput>> output = svc.ReadList(_businessEntityId);
                    response = StatusCode((int)output.HttpStatus, output);
                    return response;
                }
                else
                {
                    ModelValidation.AddModelErrors(currentErrors, ModelState);
                }
            }
            catch (Exception ex)
            {
                currentErrors.MergeWith(errorsParser.FromException(ex));
            }
            response = StatusCode((int)currentErrors.HttpStatus, new Output(currentErrors));
            return response;
        }
    }
}