//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "WPF Views - Client-Server" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System.Windows.Controls;
using Xomega.Framework.Views;

namespace AdventureWorks.Client.WpfCS
{
    public partial class LoginView
    {
        public LoginView()
        {
            InitializeComponent();
        }

        protected override Button CloseButton { get { return btnClose; } }
        protected override IErrorPresenter ErrorsPanel { get { return pnlErrors; } }
        protected override Button SaveButton { get { return btnSave; } }
    }
}