//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------


namespace AdventureWorks.Services.Entities
{
    public partial class DemoSalesOrderDetailSeed
    {
        public DemoSalesOrderDetailSeed()
        {
        }

        #region Properties

        public int LocalId  { get; set; }

        public short OrderQty  { get; set; }

        public int ProductId  { get; set; }

        public int SpecialOfferId  { get; set; }

        public int OrderId  { get; set; }

        #endregion
    }
}