//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    public partial class DemoSalesOrderHeaderSeed
    {
        public DemoSalesOrderHeaderSeed()
        {
        }

        #region Properties

        public int LocalId  { get; set; }

        public DateTime DueDate  { get; set; }

        public int CustomerId  { get; set; }

        public int SalesPersonId  { get; set; }

        public int BillToAddressId  { get; set; }

        public int ShipToAddressId  { get; set; }

        public int ShipMethodId  { get; set; }

        #endregion
    }
}