//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AdventureWorks.Services.Entities
{
    public class DemoSalesOrderDetailSeedConfig : IEntityTypeConfiguration<DemoSalesOrderDetailSeed>
    {
        public void Configure(EntityTypeBuilder<DemoSalesOrderDetailSeed> c)
        {
            c.ToTable("DemoSalesOrderDetailSeed", "Demo")
             .HasKey(e => e.LocalId);

            // configure properties
          
            c.Property(e => e.LocalId)
             .HasColumnName("LocalID")
             .HasColumnType("int")
             .IsRequired()
             .ValueGeneratedOnAdd();

            c.Property(e => e.OrderQty)
             .HasColumnName("OrderQty")
             .HasColumnType("smallint")
             .IsRequired();

            c.Property(e => e.ProductId)
             .HasColumnName("ProductID")
             .HasColumnType("int")
             .IsRequired();

            c.Property(e => e.SpecialOfferId)
             .HasColumnName("SpecialOfferID")
             .HasColumnType("int")
             .IsRequired();

            c.Property(e => e.OrderId)
             .HasColumnName("OrderID")
             .HasColumnType("int")
             .IsRequired();

        }
    }
}