//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    public partial class SalesOrderDetailOndisk
    {
        public SalesOrderDetailOndisk()
        {
        }

        #region Properties

        public int SalesOrderId  { get; set; }

        public long SalesOrderDetailId  { get; set; }

        public string CarrierTrackingNumber  { get; set; }

        public short OrderQty  { get; set; }

        public int SpecialOfferId  { get; set; }

        public int ProductId  { get; set; }

        public decimal UnitPrice  { get; set; }

        public decimal UnitPriceDiscount  { get; set; }

        public DateTime ModifiedDate  { get; set; }

        #endregion

        #region Navigation Properties

        ///<summary>
        /// SalesOrderHeaderOndisk object referenced by the field SalesOrderId.
        ///</summary>
        public virtual SalesOrderHeaderOndisk SalesOrderObject { get; set; }

        ///<summary>
        /// SpecialOfferProductOndisk object referenced by the fields SpecialOfferId, ProductId.
        ///</summary>
        public virtual SpecialOfferProductOndisk SpecialOfferProductOndiskObject { get; set; }

        #endregion
    }
}