//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    public partial class SpecialOfferProductOndisk
    {
        public SpecialOfferProductOndisk()
        {
        }

        #region Properties

        public int SpecialOfferId  { get; set; }

        public int ProductId  { get; set; }

        public DateTime ModifiedDate  { get; set; }

        #endregion

        #region Navigation Properties

        ///<summary>
        /// SpecialOfferOndisk object referenced by the field SpecialOfferId.
        ///</summary>
        public virtual SpecialOfferOndisk SpecialOfferObject { get; set; }

        ///<summary>
        /// ProductOndisk object referenced by the field ProductId.
        ///</summary>
        public virtual ProductOndisk ProductObject { get; set; }

        #endregion
    }
}