//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    public partial class SpecialOfferProductInmem
    {
        public SpecialOfferProductInmem()
        {
        }

        #region Properties

        public int SpecialOfferId  { get; set; }

        public int ProductId  { get; set; }

        public DateTime ModifiedDate  { get; set; }

        #endregion

        #region Navigation Properties

        ///<summary>
        /// SpecialOfferInmem object referenced by the field SpecialOfferId.
        ///</summary>
        public virtual SpecialOfferInmem SpecialOfferObject { get; set; }

        ///<summary>
        /// ProductInmem object referenced by the field ProductId.
        ///</summary>
        public virtual ProductInmem ProductObject { get; set; }

        #endregion
    }
}