//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    public partial class SpecialOfferOndisk
    {
        public SpecialOfferOndisk()
        {
        }

        #region Properties

        public int SpecialOfferId  { get; set; }

        public string Description  { get; set; }

        public decimal DiscountPct  { get; set; }

        public string Type  { get; set; }

        public string Category  { get; set; }

        public DateTime StartDate  { get; set; }

        public DateTime EndDate  { get; set; }

        public int MinQty  { get; set; }

        public int? MaxQty  { get; set; }

        public DateTime ModifiedDate  { get; set; }

        #endregion
    }
}