//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Blazor Views" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System.Collections.Generic;
using Xomega.Framework.Blazor.Components;

namespace AdventureWorks.Client.Blazor.Common.Views
{
    public class MainMenu
    {
        public static List<MenuItem> Items = new List<MenuItem>()
        {
            new MenuItem()
            {
                Text = "Sales",
                Items = new List<MenuItem>()
                {
                    new MenuItem()
                    {
                        Text = "Customer List",
                        Href = "CustomerListView"
                    },
                    new MenuItem()
                    {
                        Text = "New Sales Order",
                        Href = "SalesOrderView?_action=create"
                    },
                    new MenuItem()
                    {
                        Text = "Sales Order List",
                        Href = "SalesOrderListView"
                    },
                }
            },
        };
    }
}