//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "WPF Views" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using AdventureWorks.Client.ViewModels;
using System.Windows.Controls;
using Xomega.Framework.Views;

namespace AdventureWorks.Client.Wpf
{
    public partial class LoginView
    {
        protected LoginViewModel VM => Model as LoginViewModel;

        public LoginView()
        {
            InitializeComponent();
            IsAsync = true;
        }

        protected override TextBlock TitleControl => viewTitle;
        protected override Button CloseButton => btnClose;
        protected override IErrorPresenter ErrorsPanel => pnlErrors;
        protected override Button SaveButton => btnSave;
    }
}