//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;
using System.ServiceModel;
using Xomega.Framework;
using Xomega.Framework.Services;

namespace AdventureWorks.Services
{
    #region ISalesTerritoryService interface

    ///<summary>
    /// Sales territory lookup table.
    ///</summary>
    [ServiceContract]
    public interface ISalesTerritoryService
    {

        ///<summary>
        /// Reads a list of Sales Territory objects based on the specified criteria.
        ///</summary>
        [OperationContract]
        [FaultContract(typeof(ErrorList))]
        Output<ICollection<SalesTerritory_ReadListOutput>> ReadList();

    }
    #endregion

    #region SalesTerritory_ReadListOutput structure

    ///<summary>
    /// The output structure of operation ISalesTerritoryService.ReadList.
    ///</summary>
    [DataContract]
    public class SalesTerritory_ReadListOutput
    {
        
        [DataMember]
        public int TerritoryId { get; set; }
        
        ///<summary>
        /// Sales territory description
        ///</summary>
        [DataMember]
        public string Name { get; set; }
        
        ///<summary>
        /// ISO standard country or region code. Foreign key to CountryRegion.CountryRegionCode. 
        ///</summary>
        [DataMember]
        public string CountryRegionCode { get; set; }
        
        ///<summary>
        /// Geographic area to which the sales territory belong.
        ///</summary>
        [DataMember]
        public string Group { get; set; }
    }
    #endregion

}