//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    public partial class PersonJson
    {
        public PersonJson()
        {
        }

        #region Properties

        public int PersonId  { get; set; }

        public string PersonType  { get; set; }

        public bool NameStyle  { get; set; }

        public string Title  { get; set; }

        public string FirstName  { get; set; }

        public string MiddleName  { get; set; }

        public string LastName  { get; set; }

        public string Suffix  { get; set; }

        public int EmailPromotion  { get; set; }

        public string AdditionalContactInfo  { get; set; }

        public string Demographics  { get; set; }

        public Guid Rowguid  { get; set; }

        public DateTime ModifiedDate  { get; set; }

        #endregion
    }
}