//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "EF Domain Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Entities
{
    public partial class PersonTemporal
    {
        public PersonTemporal()
        {
        }

        #region Properties

        public int BusinessEntityId  { get; set; }

        public string PersonType  { get; set; }

        public bool NameStyle  { get; set; }

        public string Title  { get; set; }

        public string FirstName  { get; set; }

        public string MiddleName  { get; set; }

        public string LastName  { get; set; }

        public string Suffix  { get; set; }

        public int EmailPromotion  { get; set; }

        public DateTime ValidFrom  { get; set; }

        public DateTime ValidTo  { get; set; }

        #endregion
    }
}