//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "ASP.NET Views" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

namespace AdventureWorks.Client.Web
{
    public partial class SalesOrderDetailView
    {
        protected global::System.Web.UI.WebControls.Panel pnlComposition;
        protected global::System.Web.UI.WebControls.Panel pnlMain;
        protected global::System.Web.UI.WebControls.Label lblSubcategory;
        protected global::System.Web.UI.WebControls.DropDownList ctlSubcategory;
        protected global::System.Web.UI.WebControls.Label lblProductId;
        protected global::System.Web.UI.WebControls.DropDownList ctlProductId;
        protected global::System.Web.UI.WebControls.Label lblOrderQty;
        protected global::System.Web.UI.WebControls.TextBox ctlOrderQty;
        protected global::System.Web.UI.WebControls.Label lblSpecialOfferId;
        protected global::System.Web.UI.WebControls.DropDownList ctlSpecialOfferId;
        protected global::System.Web.UI.WebControls.Label lblUnitPrice;
        protected global::System.Web.UI.WebControls.Label ctlUnitPrice;
        protected global::System.Web.UI.WebControls.Label lblUnitPriceDiscount;
        protected global::System.Web.UI.WebControls.Label ctlUnitPriceDiscount;
        protected global::System.Web.UI.WebControls.Label lblLineTotal;
        protected global::System.Web.UI.WebControls.Label ctlLineTotal;
        protected global::System.Web.UI.WebControls.Label lblCarrierTrackingNumber;
        protected global::System.Web.UI.WebControls.TextBox ctlCarrierTrackingNumber;
    }
}